import { readFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));

// v8 Phase 6 — generates a self-contained userscript (Violentmonkey/Tampermonkey-compatible) that
// autofills an ATS application form with one application's apply-pack data, entirely client-side,
// in the user's own browser session, triggered only by a fresh click. See CLAUDE.md's
// "no autonomous submission" rule and the v8 plan's Phase 6 section for the full spec this
// implements — every guard below is load-bearing, not decorative.
//
// Layering (per the plan, all three required, none optional):
//   1. In-app copy panel (ui/src/components/ApplyPanel.tsx) — the floor, already built (Phase 5).
//   2. This generated userscript — the main deliverable.
//   3. A bookmarklet wrapper (built client-side in ApplyPanel.tsx from this same script text) —
//      documented everywhere as "may be blocked by page CSP", never positioned as primary.
//
// Data is inlined into the generated text at request time (see routes/applyAssist.ts) rather than
// fetched by the running script — there is deliberately no runtime callback to localhost from the
// page the userscript runs on. That also means "auto-update" (@updateURL below) really only means
// "re-install picks up this application's current data" — it does NOT mean the script periodically
// re-fetches anything on its own. Said plainly in a code comment below so a future reader doesn't
// oversell it.
//
// Honesty about the ceiling (also surfaced in ApplyPanel.tsx's install instructions): Greenhouse/
// Lever/Ashby-style plain HTML forms fill well. iCIMS is fair. Workday's custom, non-native
// dropdowns mostly do NOT respond to a plain `.value =` assignment (React's controlled-input state
// doesn't see it) — this script does use the native-setter + dispatched-event trick for text inputs,
// which helps React-controlled `<input>`s, but a fully custom combobox widget (no real `<select>`,
// no real `<input>`) will still typically fall back to "flagged, not filled." That is expected, not
// a bug to chase down.

const CORE_MODULE_PATH = join(__dirname, "fieldMatcherCore.js");

// Strips the `export ` keyword from each top-level declaration line so fieldMatcherCore.js's exact
// algorithm (single source of truth, unit-tested directly) becomes a plain script body with no
// ES module import/export syntax — safe to concatenate into a userscript that has no bundler and
// runs in a userscript manager's isolated world (which does not support `import`/`export`).
function embeddableCoreSource(): string {
  const raw = readFileSync(CORE_MODULE_PATH, "utf8");
  return raw.replace(/^export (function|const)/gm, "$1");
}

export interface ApplyAssistData {
  applicationId: string;
  organization: string;
  title: string;
  postingUrl: string | null;
  identity: Record<string, unknown> | null;
  resolvedAnswers: Array<{ question: string | null; questionKey: string | null; text: string }>;
}

// The ATS domains this project's scrapers actually cover (scrapers/src/sources.config.ts), plus the
// generic hosted-ATS domains those adapters point at — grounded in real data, not guessed. Workday
// tenants are per-org subdomains of myworkdayjobs.com, which the wildcard covers.
export const USERSCRIPT_MATCH_PATTERNS = [
  "*://*.greenhouse.io/*",
  "*://job-boards.greenhouse.io/*",
  "*://jobs.lever.co/*",
  "*://*.myworkdayjobs.com/*",
  "*://*.icims.com/*",
  "*://*.ultipro.com/*",
  "*://*.rec.pro.ukg.net/*",
  "*://*.aaimtrack.com/*",
  "*://jobs.ashbyhq.com/*",
];

function escapeForScriptString(json: string): string {
  // Prevents a `</script>`-style sequence (or a literal backtick) in any free-text field
  // (e.g. an answer snippet, a notes field folded into the payload) from breaking out of the
  // template-literal payload embedding below.
  return json.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/<\/script/gi, "<\\/script");
}

export function generateApplyAssistScript(data: ApplyAssistData): string {
  const payloadJson = escapeForScriptString(JSON.stringify(data));
  const coreSource = embeddableCoreSource();
  const safeTitle = data.title.replace(/[\r\n]/g, " ");
  const safeOrg = data.organization.replace(/[\r\n]/g, " ");

  return `// ==UserScript==
// @name         Apply Assist — ${safeOrg} — ${safeTitle}
// @namespace    job-app-system.local
// @version      1.0.${Date.now()}
// @description  One-click, one-application autofill helper generated by the local job-app-system. Never submits anything.
// @match        ${USERSCRIPT_MATCH_PATTERNS.join("\n// @match        ")}
// @grant        none
// @run-at       document-idle
// ==/UserScript==

// Generated by job-app-system's apply-assist helper for ONE specific application
// (id: ${data.applicationId}). Re-run the generating request (re-install) to refresh this
// application's data — this script does not fetch anything at runtime, from localhost or
// anywhere else, and "@updateURL" style auto-update is not wired up beyond that: there is no
// periodic background refresh, only "install again to get fresh data."
//
// SAFETY GUARDS (see CLAUDE.md's "no autonomous submission" rule and the v8 plan's Phase 6):
//   - This script NEVER calls the DOM submit/click APIs. It fills fields and stops. Full stop.
//   - Nothing runs until a real, fresh click on the on-page "Fill this form" button this script
//     injects — reloading or re-triggering requires clicking again, every time.
//   - Never overwrites a field that already has a non-empty value.
//   - Skips password/SSN/payment/file/hidden fields entirely, by both type and name pattern.
//   - Every field it touches gets a visible outline plus a title tooltip naming its data source.
//     EEO fields (gender/race/disability/veteran) get a visually distinct "review me" outline.
//   - Ends with an on-screen summary banner, including an Undo control, and the literal phrase
//     "Nothing was submitted."
(function () {
  "use strict";

  // ---- Inlined field-matching core (fieldMatcherCore.js, verbatim minus ESM export keywords) ----
  ${coreSource}

  // ---- This application's data, inlined at generation time (no runtime fetch) ----
  const APPLY_DATA = JSON.parse(\`${payloadJson}\`);

  // ---------------------------------------------------------------------------------------------
  // DOM extraction: turn real form elements into the plain descriptors scoreField()/assignFields()
  // expect. Kept separate from the pure-logic core above so the core stays testable without a DOM.
  // ---------------------------------------------------------------------------------------------
  function resolveLabelText(el) {
    if (el.labels && el.labels.length > 0) return Array.from(el.labels).map((l) => l.textContent || "").join(" ");
    if (el.id) {
      const forLabel = document.querySelector('label[for="' + CSS.escape(el.id) + '"]');
      if (forLabel) return forLabel.textContent || "";
    }
    const closestLabel = el.closest("label");
    if (closestLabel) return closestLabel.textContent || "";
    return "";
  }

  function resolveAriaText(el) {
    const ariaLabel = el.getAttribute("aria-label");
    if (ariaLabel) return ariaLabel;
    const labelledBy = el.getAttribute("aria-labelledby");
    if (labelledBy) {
      return labelledBy
        .split(/\\s+/)
        .map((id) => (document.getElementById(id) ? document.getElementById(id).textContent : ""))
        .join(" ");
    }
    return "";
  }

  function descriptorFor(el) {
    return {
      autocomplete: el.getAttribute("autocomplete") || "",
      name: el.getAttribute("name") || "",
      id: el.getAttribute("id") || "",
      labelText: resolveLabelText(el),
      ariaText: resolveAriaText(el),
      placeholder: el.getAttribute("placeholder") || "",
      type: (el.getAttribute("type") || el.tagName || "").toLowerCase(),
    };
  }

  // Native-setter + dispatched-event trick: plain \`el.value = x\` does not notify a React (or
  // similar) controlled input of the change, so its internal state silently disagrees with the DOM
  // — the value visually appears then reverts, or validation never sees it. Getting the *native*
  // setter for the element's own prototype and calling it, then dispatching a real "input" event,
  // is what makes React-controlled text inputs (Greenhouse/Lever/Ashby, and React-based iCIMS/
  // Workday text fields) pick up the change. This does NOT fix genuinely custom, non-native
  // dropdown widgets (Workday's combobox-style pickers) — those have no native value setter to hook
  // at all, and are expected to fall back to "flagged, not filled." See the honesty note above.
  function setNativeValue(el, value) {
    const proto = Object.getPrototypeOf(el);
    const descriptor = Object.getOwnPropertyDescriptor(proto, "value");
    if (descriptor && descriptor.set) {
      descriptor.set.call(el, value);
    } else {
      el.value = value;
    }
    el.dispatchEvent(new Event("input", { bubbles: true }));
    el.dispatchEvent(new Event("change", { bubbles: true }));
  }

  const FILL_OUTLINE = "2px solid #2563eb"; // normal fill — blue
  const REVIEW_OUTLINE = "3px dashed #d97706"; // EEO / flag-for-review — amber, visually distinct
  const UNMATCHED_REQUIRED_OUTLINE = "3px dotted #dc2626"; // unmatched but required — red

  function markField(el, outline, title) {
    el.style.outline = outline;
    el.style.outlineOffset = "1px";
    el.title = title;
  }

  function isEmptyValue(el) {
    if (el.type === "checkbox" || el.type === "radio") return !el.checked;
    return !el.value || !String(el.value).trim();
  }

  // Runs exactly once per real click of the injected button — see the IIFE-scoped click handler
  // at the bottom, which is the ONLY place this function is invoked.
  function runFill() {
    const identity = APPLY_DATA.identity || {};
    const undoLog = []; // [{el, prevValue, prevChecked}] — restored verbatim by the Undo button.
    let filledCount = 0;
    let flaggedCount = 0;
    let skippedSensitiveCount = 0;

    const textInputs = Array.from(
      document.querySelectorAll('input:not([type]), input[type="text"], input[type="email"], input[type="tel"], input[type="url"], input[type="date"], textarea')
    );
    const textDescriptors = textInputs.map(descriptorFor);

    const textTargets = TARGET_FIELDS.filter((t) => t.kind === "text");
    const eligibleIndexes = [];
    const eligibleDescriptors = [];
    textInputs.forEach((el, i) => {
      if (isSensitiveField(textDescriptors[i])) {
        skippedSensitiveCount++;
        return;
      }
      eligibleIndexes.push(i);
      eligibleDescriptors.push(textDescriptors[i]);
    });

    const assignments = assignFields(eligibleDescriptors, textTargets);
    assignments.forEach((assignment) => {
      const el = textInputs[eligibleIndexes[assignment.fieldIndex]];
      const target = textTargets.find((t) => t.key === assignment.targetKey);
      const value = identity[assignment.targetKey];
      if (!value) return; // nothing to fill even if matched
      if (assignment.tier === "ignore") return;
      if (!isEmptyValue(el)) return; // never overwrite a non-empty field

      if (assignment.tier === "flag") {
        markField(el, REVIEW_OUTLINE, "Low-confidence match for: " + target.label + " (not filled — verify manually)");
        flaggedCount++;
        return;
      }

      undoLog.push({ el, prevValue: el.value });
      setNativeValue(el, String(value));
      markField(el, FILL_OUTLINE, "Filled from: " + target.label);
      filledCount++;
    });

    // Select/radio-group targets (EEO + yes/no) — matched by visible option text, not by
    // scoreField's autocomplete/name/label signals, since these are option-set fields.
    const optionTargets = TARGET_FIELDS.filter((t) => t.kind === "option");
    const selects = Array.from(document.querySelectorAll("select"));
    selects.forEach((select) => {
      const descriptor = descriptorFor(select);
      if (isSensitiveField(descriptor)) return;
      let bestTarget = null;
      let bestScore = 0;
      optionTargets.forEach((target) => {
        const score = scoreField(descriptor, target);
        if (score > bestScore) {
          bestScore = score;
          bestTarget = target;
        }
      });
      if (!bestTarget || bestScore < FLAG_THRESHOLD) return;
      const storedValue = identity[bestTarget.key + "Label"] !== undefined ? identity[bestTarget.key + "Label"] : identity[bestTarget.key];
      const storedLabel =
        typeof storedValue === "boolean" ? (storedValue ? "Yes" : "No") : storedValue;
      if (!storedLabel) return;

      const optionTexts = Array.from(select.options).map((o) => o.textContent || "");
      const matchIndex = matchOptionLabel(optionTexts, String(storedLabel));

      if (bestScore < FILL_THRESHOLD || matchIndex === -1) {
        markField(select, REVIEW_OUTLINE, "Possible match for: " + bestTarget.label + " (verify manually)");
        flaggedCount++;
        return;
      }
      if (!isEmptyValue(select)) return;

      undoLog.push({ el: select, prevValue: select.value });
      select.selectedIndex = matchIndex;
      select.dispatchEvent(new Event("change", { bubbles: true }));
      markField(select, bestTarget.isEEO ? REVIEW_OUTLINE : FILL_OUTLINE, "Filled from: " + bestTarget.label + (bestTarget.isEEO ? " (EEO — please review)" : ""));
      filledCount++;
    });

    // Unmatched but DOM-required fields get flagged too, even though nothing about them scored —
    // this is a distinct signal ("you still need to fill this yourself"), not a match at all.
    const allFormFields = Array.from(document.querySelectorAll("input[required], select[required], textarea[required]"));
    let unmatchedRequiredCount = 0;
    allFormFields.forEach((el) => {
      if (el.style.outline === FILL_OUTLINE || el.style.outline === REVIEW_OUTLINE) return;
      if (!isEmptyValue(el)) return;
      const descriptor = descriptorFor(el);
      if (isSensitiveField(descriptor)) return;
      markField(el, UNMATCHED_REQUIRED_OUTLINE, "Required field — no confident match found, please fill manually");
      unmatchedRequiredCount++;
    });

    showSummaryBanner({ filledCount, flaggedCount, skippedSensitiveCount, unmatchedRequiredCount, undoLog });
  }

  function showSummaryBanner({ filledCount, flaggedCount, skippedSensitiveCount, unmatchedRequiredCount, undoLog }) {
    const existing = document.getElementById("job-app-system-apply-assist-banner");
    if (existing) existing.remove();

    const banner = document.createElement("div");
    banner.id = "job-app-system-apply-assist-banner";
    banner.style.cssText =
      "position:fixed;bottom:16px;right:16px;z-index:2147483647;background:#111827;color:#f9fafb;" +
      "padding:12px 16px;border-radius:8px;font:13px/1.4 -apple-system,sans-serif;max-width:340px;" +
      "box-shadow:0 4px 16px rgba(0,0,0,.3);";

    const summaryText =
      "Filled " + filledCount + ", flagged " + flaggedCount + " for review" +
      (unmatchedRequiredCount > 0 ? ", " + unmatchedRequiredCount + " required field(s) need manual entry" : "") +
      ", skipped " + skippedSensitiveCount + " (sensitive). Nothing was submitted.";

    const text = document.createElement("div");
    text.textContent = summaryText;
    banner.appendChild(text);

    const undoButton = document.createElement("button");
    undoButton.textContent = "Undo";
    undoButton.style.cssText =
      "margin-top:8px;padding:4px 10px;border-radius:4px;border:none;background:#374151;color:#fff;cursor:pointer;";
    undoButton.addEventListener("click", function (ev) {
      if (!ev.isTrusted) return;
      undoLog.forEach(function (entry) {
        setNativeValue(entry.el, entry.prevValue);
        entry.el.style.outline = "";
        entry.el.title = "";
      });
      banner.remove();
    });
    banner.appendChild(undoButton);

    const closeButton = document.createElement("button");
    closeButton.textContent = "Dismiss";
    closeButton.style.cssText =
      "margin-top:8px;margin-left:6px;padding:4px 10px;border-radius:4px;border:none;background:transparent;color:#9ca3af;cursor:pointer;";
    closeButton.addEventListener("click", function (ev) {
      if (!ev.isTrusted) return;
      banner.remove();
    });
    banner.appendChild(closeButton);

    document.body.appendChild(banner);
  }

  function injectTriggerButton() {
    if (document.getElementById("job-app-system-apply-assist-button")) return;
    const button = document.createElement("button");
    button.id = "job-app-system-apply-assist-button";
    button.textContent = "Fill this form (Apply Assist)";
    button.style.cssText =
      "position:fixed;bottom:16px;left:16px;z-index:2147483647;padding:8px 14px;border-radius:6px;" +
      "border:none;background:#1d4ed8;color:#fff;font:13px/1.2 -apple-system,sans-serif;cursor:pointer;" +
      "box-shadow:0 4px 12px rgba(0,0,0,.25);";
    // The ONLY invocation of runFill() anywhere in this script — requires a fresh, real
    // (isTrusted) click every single time. There is no auto-run path, and running the page's
    // form twice requires two separate clicks, since runFill() holds no persistent "already ran"
    // state that would let a script-dispatched event replay it.
    button.addEventListener("click", function (ev) {
      if (!ev.isTrusted) return;
      runFill();
    });
    document.body.appendChild(button);
  }

  if (document.readyState === "complete" || document.readyState === "interactive") {
    injectTriggerButton();
  } else {
    document.addEventListener("DOMContentLoaded", injectTriggerButton);
  }
})();
`;
}
